getCookie = (name) ->
	matches = document.cookie.match(new RegExp('(?:^|; )' + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + '=([^;]*)'))
	if matches then decodeURIComponent(matches[1]) else undefined
	# ---
	# generated by js2coffee 2.2.0

setCookie = (name, value, exlpiration_days) ->
	date = new Date(Date.now() + 86400e3*exlpiration_days)
	date = date.toUTCString()
	document.cookie = encodeURIComponent(name) + '=' + encodeURIComponent(value) + "; expires=" + date
	return

deleteCookie = (name) ->
	setCookie name, '', 'max-age': -1
	return
	# ---
	# generated by js2coffee 2.2.0
