// Generated by CoffeeScript 2.5.1
var birthdateFocusinHandler, birthdateFocusoutHandler, birthday_pattern, fnsFocusinHandler, fnsFocusoutHandler, genderFocusinHandler, genderFocusoutHandler, initValidElements, mailFocusinHandler, mailFocusoutHandler, mail_pattern, messageFocusinHandler, messageFocusoutHandler, qHowManyTextWord, telefFocusinHandler, telefFocusoutHandler, telef_pattern, validMessageForm, validTest;

telef_pattern = /(\+[3|7]\d{10})|\d{9}/;

mail_pattern = /[0-9a-z_-]+@[0-9a-z_-]+\.[a-z]{2,5}/i;

birthday_pattern = /^\d{1,2}\.\d{1,2}\.\d{4}$/;

validMessageForm = function() {
  var result;
  result = false;
  if ($(".invalid").eq(0).length === 0) {
    $("#messageForm").css("display", "none");
    $("#MessageFormSubmitedMessage").css("display", "inline");
    result = true;
  } else {
    event.preventDefault();
  }
  return result;
};

$(function() {
  initDateElements();
  initValidElements();
});

// ---
// generated by js2coffee 2.2.0
qHowManyTextWord = function(message) {
  var dec;
  dec = 0;
  message = message.trim();
  if (message.length > 0) {
    if (message.charAt(0) === " ") {
      dec++;
    }
    if (message.length > 1) {
      if (message.charAt(message.length - 1) === " ") {
        dec++;
      }
    }
  }
  return message.split(" ").length - dec;
};

validTest = function() {
  if ($(".invalid").eq(0).length === 0 && $(".valid").length === 6) {
    $("#submit-button").css("pointer-events", "auto").disabled = false;
  }
};

fnsFocusinHandler = function() {
  $("input[name=familyNameSurname]").addClass("focused").removeClass("valid").removeClass("invalid");
  $("#submit-button").prop("disabled", true);
};

fnsFocusoutHandler = function() {
  $("input[name=familyNameSurname]").removeClass("focused");
  if ($("input[name=familyNameSurname]").val() === "") {
    $("#valid01").css("display", "inline");
    $("input[name=familyNameSurname]").addClass("invalid");
  } else {
    $("#valid01").css("display", "none");
    if ($("input[name=familyNameSurname]").val() === ' ') {
      $("#valid02").css("display", "inline");
      $("input[name=familyNameSurname]").addClass("invalid");
    } else {
      $("#valid02").css("display", "none");
      if ($("input[name=familyNameSurname]").val().charAt(0) === ' ') {
        $("#valid03").css("display", "inline");
        $("input[name=familyNameSurname]").addClass("invalid");
      } else {
        $("#valid03").css("display", "none");
        if ($("input[name=familyNameSurname]").val() === "Фамилия Имя Отчество") {
          $("#valid04").css("display", "inline");
          $("input[name=familyNameSurname]").addClass("invalid");
        } else {
          $("#valid04").css("display", "none");
          if (qHowManyTextWord($("input[name=familyNameSurname]").val()) < 3) {
            $("#valid05").css("display", "inline");
            $("input[name=familyNameSurname]").addClass("invalid");
          } else {
            $("#valid05").css("display", "none");
            if (qHowManyTextWord($("input[name=familyNameSurname]").val()) > 3) {
              $("#valid06").css("display", "inline");
              $("input[name=familyNameSurname]").addClass("invalid");
            } else {
              $("#valid06").css("display", "none");
              $("input[name=familyNameSurname]").addClass("valid");
              // TODO: jquery disabled
              if ($(".invalid").eq(0).length === 0) {
                $("#submit-button").prop("disabled", false);
              }
            }
          }
        }
      }
    }
  }
  validTest();
};

genderFocusinHandler = function() {
  $("#genderOutline").addClass("focused").removeClass("valid").removeClass("invalid");
  return $("#submit-button").prop("disabled", true);
};

genderFocusoutHandler = function() {
  $("#genderOutline").removeClass("focused");
  if ($("input[name=gender]").is(":checked") === false) {
    $("#valid11").css("display", "inline");
    $("#genderOutline").addClass("invalid");
  } else {
    $("#valid11").css("display", "none");
    $("#genderOutline").addClass("valid");
    if ($(".invalid").eq(0).length === 0) {
      $("#submit-button").prop("disabled", false);
    }
  }
  validTest();
};

telefFocusinHandler = function() {
  $("input[name=telef]").addClass("focused").removeClass("valid").removeClass("invalid");
  $("#submit-button").prop("disabled", true);
};

telefFocusoutHandler = function() {
  $("input[name=telef]").removeClass("focused");
  if ($("input[name=telef]").val().length > 12 || $("input[name=telef]").val().length < 9) {
    $("#valid201").css("display", "inline");
    $("input[name=telef]").addClass("invalid");
  } else {
    $("#valid201").css("display", "none");
    if (telef_pattern.test($("input[name=telef]").val()) === false) {
      $("#valid20").css("display", "inline");
      $("input[name=telef]").addClass("invalid");
    } else {
      $("#valid20").css("display", "none");
      $("input[name=telef]").addClass("valid");
      if ($(".invalid").eq(0).length === 0) {
        $("#submit-button").prop("disabled", false);
      }
    }
  }
  validTest();
};

mailFocusinHandler = function() {
  $("input[name=mail]").addClass("focused").removeClass("valid").removeClass("invalid");
  $("#submit-button").prop("disabled", true);
};

mailFocusoutHandler = function() {
  $("input[name=mail]").removeClass("focused");
  if (mail_pattern.test($("input[name=mail]").val()) === false) {
    $("#valid21").css("display", "inline");
    $("input[name=mail]").addClass("invalid");
  } else {
    $("#valid21").css("display", "none");
    $("input[name=mail]").addClass("valid");
    if ($(".invalid").eq(0).length === 0) {
      $("#submit-button").prop("disabled", false);
    }
  }
  validTest();
};

messageFocusinHandler = function() {
  $("input[name=message]").addClass("focused").removeClass("valid").removeClass("invalid");
  if ($(".invalid").eq(0).length !== 0) {
    $("#submit-button").prop("disabled", true);
  }
};

messageFocusoutHandler = function() {
  $("input[name=message]").removeClass("focused");
  if ($("input[name=message]").val() === "") {
    $("#valid31").css("display", "inline");
    $("input[name=message]").addClass("invalid");
  } else {
    $("#valid31").css("display", "none");
    if ($("input[name=message]").val() === "текст сообщения") {
      $("#valid32").css("display", "inline");
      $("input[name=message]").addClass("invalid");
    } else {
      $("#valid32").css("display", "none");
      $("input[name=message]").addClass("valid");
      if ($(".invalid").eq(0).length === 0) {
        $("#submit-button").prop("disabled", false);
      }
    }
  }
  validTest();
};

birthdateFocusinHandler = function() {
  $("input[name=birthdate]").addClass("focused").removeClass("valid").removeClass("invalid");
  $("#submit-button").prop("disabled", true);
  if ($("input[name=birthdate]").val().split('.') !== 3) {
    $("input[name=birthdate]").val("31.12.1999");
  }
};

birthdateFocusoutHandler = function() {
  $("input[name=birthdate]").removeClass("focused");
  if ($("input[name=birthdate]").val() === '' || birthday_pattern.test($("input[name=birthdate]").val()) === false) {
    $("#valid41").css("display", "inline");
    $("input[name=birthdate]").addClass("invalid");
  } else {
    $("#valid41").css("display", "none");
    $("input[name=birthdate]").addClass("valid");
    if ($(".invalid").eq(0).length === 0) {
      $("#submit-button").prop("disabled", false);
    }
  }
  validTest();
};

initValidElements = function() {
  $("input[name=familyNameSurname]").focusin(fnsFocusinHandler).focusout(fnsFocusoutHandler).attr("data-toggle", "popover").attr("title", "Tips (popover):").attr("data-content", "Поле должно содержать три слова разделенных пробелами для прохождения валидации по потере фокуса");
  $("#genderOutline").attr("data-toggle", "popover").attr("title", "Tips (popover):").attr("data-content", "Отметьте радиобоксом пол для прохождения валидации по потере фокуса");
  $('input[name=gender]').each(function() {
    $(this).focusin(genderFocusinHandler).focusout(genderFocusoutHandler);
  });
  // ---
  // generated by js2coffee 2.2.0
  $("input[name=gender]").eq(0).focus();
  $("input[name=telef]").focusin(telefFocusinHandler).focusout(telefFocusoutHandler).attr("data-toggle", "popover").attr("title", "Tips (popover):").attr("data-content", "Заполните номер телефона (от 9 до 11 цифр на +3 и +7) для прохождения валидации по потере фокуса").focus();
  $("input[name=mail]").focusin(mailFocusinHandler).focusout(mailFocusoutHandler).attr("data-toggle", "popover").attr("title", "Tips (popover):").attr("data-content", "Заполните действительный адрес электронной почты для прохождения валидации по потере фокуса").focus();
  $("input[name=message]").focusin(messageFocusinHandler).focusout(messageFocusoutHandler).attr("data-toggle", "popover").attr("title", "Tips (popover):").attr("data-content", "Заполните сообщение, отражающего суть обращения, для прохождения валидации по потере фокуса").focus();
  $("input[name=birthdate]").focusin(birthdateFocusinHandler).focusout(birthdateFocusoutHandler).attr("data-toggle", "popover").attr("title", "Tips (popover):").attr("data-content", "заполните дату рождения в формате ДД.ММ.ГГГГ	для прохождения валидации по потере фокуса").focus();
  $("#submitReset").attr("data-toggle", "popover").attr("title", "Tips (popover):").attr("data-content", "Для отправки необходимо заполнить поля формы и пройти валидацию по потере фокуса").children("input[type=submit]").css("pointer-events", "none").addClass("btn").addClass("btn-success");
  $("#submitReset").children("input[type=reset]").addClass("btn").addClass("btn-warning");
  $("input[name=familyNameSurname]").focus();
  $('[data-toggle="popover"]').popover({
    trigger: 'hover',
    delay: {
      'show': 100,
      'hide': 500
    }
  });
};

// ---
// generated by js2coffee 2.2.0
