// Generated by CoffeeScript 2.5.1
var list;

list = function(type) {
  var arr, item;
  arr = [];
  for (var i = 1; i < list.arguments.length; i++) arr.push("<LI>"+list.arguments[i]+"</LI>");
  document.write(`<${type}L>`);
  document.write((function() {
    var i, len, results;
    results = [];
    for (i = 0, len = arr.length; i < len; i++) {
      item = arr[i];
      results.push(item);
    }
    return results;
  })());
  return document.write(`</${type}L>`);
};
