// Generated by CoffeeScript 2.5.1
var list;

list = function() {
  var i, j, len, ref;
  document.write("<" + list.arguments[0] + "L>");
  ref = [].slice.call(list.arguments).slice(1);
  for (j = 0, len = ref.length; j < len; j++) {
    i = ref[j];
    document.write("<LI>" + i + "</LI>");
  }
  return document.write("</" + list.arguments[0] + "L>");
};
