// Generated by CoffeeScript 2.5.1
(function() {
  var list;

  list = function(type, ...list) {
    var i;
    document.write("<" + type + "L>");
    document.write((function() {
      var j, len, ref, results;
      ref = list + "</LI>";
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        i = ref[j];
        results.push("<LI>" + i);
      }
      return results;
    })());
    return document.write("</" + type + "L>");
  };

}).call(this);
